
- name: start the service
  systemd:
    state: started
    daemon_reload: yes
    name: "{{ service_name }}"
    enabled: yes
  become: yes

#- name: wait for service to start
#  uri:
#    url: "https://localhost:{{ health_check_port | default(server_port) }}{{ health_check_uri | default('/actuator/health') }}"
#    return_content: yes
#    validate_certs: false
#  register: _result
#  until: _result.status == 200
#  retries: 10
#  delay: 3
#  #failed_when: "'UP' not in _result.content"
